# Generated by Django 4.0.4 on 2023-02-06 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField(auto_now_add=True)),
                ('genetics', models.CharField(blank=True, max_length=200, null=True)),
                ('seedbank', models.CharField(blank=True, max_length=80, null=True)),
                ('fixture', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_day', models.FloatField(blank=True, null=True)),
                ('temperature_night', models.FloatField(blank=True, null=True)),
                ('humidity_day', models.FloatField(blank=True, null=True)),
                ('humidity_night', models.FloatField(blank=True, null=True)),
                ('pH', models.FloatField(blank=True, null=True)),
                ('ec', models.FloatField(blank=True, null=True)),
                ('phase', models.CharField(choices=[('seedling', 'Seedling'), ('vegetative', 'Vegetative'), ('bloom', 'Bloom')], max_length=12)),
                ('irrigation', models.FloatField(blank=True, null=True)),
                ('light_height', models.FloatField(blank=True, null=True)),
                ('light_power', models.FloatField(blank=True, null=True)),
                ('calibration', models.BooleanField(blank=True, default=False, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Logs', to='records.cycle')),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('brand', models.CharField(max_length=80)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NutrientLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration', models.FloatField()),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.log')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.nutrient')),
            ],
        ),
    ]
