# Generated by Django 4.0.4 on 2023-02-05 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField(auto_now_add=True)),
                ('genetics', models.CharField(blank=True, max_length=200, null=True)),
                ('seedbank', models.CharField(blank=True, max_length=80, null=True)),
                ('fixture', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_day', models.FloatField(blank=True, null=True)),
                ('temperature_night', models.FloatField(blank=True, null=True)),
                ('humidity_day', models.FloatField(blank=True, null=True)),
                ('humidity_night', models.FloatField(blank=True, null=True)),
                ('pH', models.FloatField(blank=True, null=True)),
                ('ec', models.FloatField(blank=True, null=True)),
                ('irrigation', models.FloatField(blank=True, null=True)),
                ('light_height', models.FloatField(blank=True, null=True)),
                ('light_power', models.FloatField(blank=True, null=True)),
                ('calibration', models.BooleanField(blank=True, default=False, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayLogs', to='records.cycle')),
                ('nutrients', models.ManyToManyField(blank=True, to='records.nutrient')),
            ],
        ),
        migrations.AddField(
            model_name='cycle',
            name='day_logs',
            field=models.ManyToManyField(blank=True, related_name='cycles', to='records.daylog'),
        ),
    ]
