# Generated by Django 4.0.4 on 2023-02-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_log_phase_day_log_total_days_alter_nutrientlog_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='phase_day',
        ),
        migrations.RemoveField(
            model_name='log',
            name='total_days',
        ),
    ]
