# Generated by Django 4.0.4 on 2023-02-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_remove_log_phase_day_remove_log_total_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='phase_day',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
