# Generated by Django 4.0.4 on 2023-02-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_nutrient_featured_image_alter_log_humidity_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='light_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='light_power',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
