# Generated by Django 4.0.4 on 2023-02-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_log_water'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='light_power',
            field=models.IntegerField(blank=True, choices=[('0', 'Darkness'), ('25', '25%'), ('50', '50%'), ('75', '75%'), ('100', '100%')], null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='temperature_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='temperature_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
