# Generated by Django 4.0.4 on 2023-02-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_alter_log_light_power_alter_log_temperature_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='comment',
        ),
        migrations.AddField(
            model_name='cycle',
            name='behavioral_response',
            field=models.CharField(blank=True, choices=[('auto-flowering', 'Auto-flowering'), ('photoperiodic', 'Photoperiodic')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='fixture',
            field=models.CharField(default='Unspecified', max_length=200),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='genetics',
            field=models.CharField(default='Unspecified', max_length=200),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='log',
            name='ec',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
