# Generated by Django 4.0.4 on 2023-02-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_remove_cycle_comment_cycle_behavioral_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='fixture',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='genetics',
            field=models.CharField(max_length=200),
        ),
    ]
