# Generated by Django 4.0.4 on 2023-02-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_cycle_grow_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='seed_type',
            field=models.CharField(blank=True, choices=[('regular', 'Regular'), ('feminized', 'Feminized'), ('clones', 'Clones')], max_length=80, null=True),
        ),
    ]
