# Generated by Django 4.1.6 on 2023-03-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_cycle_seed_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='beginning_phase',
            field=models.CharField(blank=True, choices=[('seedling', 'Seedling'), ('vegetative', 'Vegetative')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='grow_medium',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='light_power',
            field=models.IntegerField(blank=True, choices=[(0, 'Darkness'), (25, '25%'), (50, '50%'), (75, '75%'), (100, '100%')], null=True),
        ),
    ]
