# Generated by Django 4.1.6 on 2023-03-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_cycle_beginning_phase_alter_cycle_grow_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='beginning_phase',
            field=models.CharField(blank=True, choices=[('seedling', 'Seedling'), ('vegetative', 'Vegetative')], default='vegetative', max_length=80, null=True),
        ),
    ]
