# Generated by Django 4.0.4 on 2023-03-08 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0018_alter_cycle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='is_submitted',
        ),
    ]
