# Generated by Django 4.0.4 on 2023-03-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_remove_cycle_is_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrient',
            name='nutrient_type',
            field=models.CharField(blank=True, choices=[('medium_conditioner', 'Medium conditioner'), ('base_line', 'Base'), ('root_expander', 'Root expander'), ('bud_strengthener', 'Bud strengthener'), ('bud_enlarger', 'Bud enlarger'), ('bud_taste', 'Bud taste'), ('unspecified', 'Unspecified')], default='unspecified', max_length=18, null=True),
        ),
    ]
