# Generated by Django 4.0.4 on 2023-03-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0020_nutrient_nutrient_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='nutrient_type',
            field=models.CharField(blank=True, choices=[('medium_conditioner', 'Medium conditioner'), ('base_line', 'Base'), ('root_expander', 'Root expander'), ('bud_strengthener', 'Bud strengthener'), ('bud_enlarger', 'Bud enlarger'), ('bud_taste', 'Bud taste')], max_length=18, null=True),
        ),
    ]
