# Generated by Django 4.0.4 on 2023-03-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0024_alter_log_options_remove_cycle_beginning_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='phase',
            field=models.CharField(choices=[('seedling', 'Seedling'), ('vegetative', 'Vegetative'), ('bloom', 'Bloom')], default='vegetative', max_length=12),
        ),
    ]
