# Generated by Django 4.0.4 on 2023-04-22 00:21

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0025_alter_log_phase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cycle',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='nutrient',
            options={'ordering': ['brand', 'nutrient_type', 'name']},
        ),
        migrations.AlterModelOptions(
            name='nutrientlog',
            options={'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(nutrient__nutrient_type='medium_conditioner', then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(nutrient__nutrient_type='base_line', then=django.db.models.expressions.Value(2)), django.db.models.expressions.When(nutrient__nutrient_type='root_expander', then=django.db.models.expressions.Value(3)), django.db.models.expressions.When(nutrient__nutrient_type='bud_strengthener', then=django.db.models.expressions.Value(4)), django.db.models.expressions.When(nutrient__nutrient_type='bud_enlarger', then=django.db.models.expressions.Value(5)), django.db.models.expressions.When(nutrient__nutrient_type='bud_taste', then=django.db.models.expressions.Value(6)))]},
        ),
        migrations.RenameField(
            model_name='log',
            old_name='water',
            new_name='carbon_dioxide',
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='nutrient_type',
            field=models.CharField(blank=True, choices=[('medium_conditioner', 'Medium conditioner'), ('base_line', 'Base'), ('root_expander', 'Root expander'), ('bud_strengthener', 'Strengthener'), ('bud_enlarger', 'Bud enlarger'), ('bud_taste', 'Bud taste')], max_length=18, null=True),
        ),
    ]
