# Generated by Django 4.0.4 on 2023-04-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0028_reservoirlog_delete_reservoir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservoirlog',
            name='status',
        ),
        migrations.AlterField(
            model_name='reservoirlog',
            name='ro',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('mix', 'Mix')], default='yes', max_length=3),
        ),
    ]
