# Generated by Django 4.0.4 on 2023-04-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0029_remove_reservoirlog_status_alter_reservoirlog_ro'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservoirlog',
            name='status',
            field=models.CharField(choices=[('refresh', 'Refresh'), ('refill', 'Refill')], default='refill', max_length=7),
        ),
    ]
