# Generated by Django 4.0.4 on 2023-05-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0030_reservoirlog_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservoirlog',
            old_name='ro',
            new_name='reverse_osmosis',
        ),
        migrations.AlterField(
            model_name='reservoirlog',
            name='status',
            field=models.CharField(choices=[('refresh', 'Refresh'), ('refill', 'Refill')], default='refill', editable=False, max_length=7),
        ),
    ]
