# Generated by Django 4.0.4 on 2023-05-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0032_rename_reverse_osmosis_reservoirlog_ro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservoirlog',
            name='ro',
        ),
        migrations.AddField(
            model_name='reservoirlog',
            name='reverse_osmosis',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
        ),
        migrations.AddField(
            model_name='reservoirlog',
            name='ro_amount',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
