# Generated by Django 4.1.6 on 2023-05-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0034_alter_reservoirlog_water'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycle',
            old_name='behavioral_response',
            new_name='reproductive_cycle',
        ),
    ]
